[build]
  publish = "site"
  functions = "functions"

[context.production]
  [context.production.environment]
    MY_API_PARAM_DEFAULT = "page=2"
    MY_API_URL_DEFAULT = "https://reqres.in/api/users"
